[general]
import = ["~/.config/alacritty/themes/themes/tokyo_night.toml"]

[window]
title = "Terminal"

[scrolling]
history = 100000

[font]
size = 8

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[env]
TERM = "xterm-256color"
